<?php
 	require "TestDB.php";
 	require "TestDB2.php";

 	if($_SERVER['REQUEST_METHOD']=='POST'){
 		// Always return JSON format
 		header('Content-Type: application/json');

 		// Sign up
 		if($_POST['isSignup']==1){
	 		$user_name = $_POST['user_name'];
	 		$return=[];
	 		$isError = 0;

	 		// check if username or email has been already in the database
	 		// prepare and bind parameters
	 		$username_sql = $conn->prepare("SELECT * FROM userdata WHERE user_name=?");
	 		$username_sql->bind_param("s",$user_name);

	 		// execute query 
	 		$username_sql->execute();

	 		$username_sql->store_result();
	 		
	 		// duplicate username
	 		if($username_sql->num_rows>0){
	 			$return['error_msg'] = "Username has been used !";
	 			$return['active'] = 1;
	 			echo json_encode($return,JSON_PRETTY_PRINT);
	 			exit;
	 		}

	 		// creates a new password hash using a strong one-way hashing algorithm.
	 		// a random salt will be generated by password_hash() for each password hashed
	 		$pass_word = password_hash($_POST['pass_word'], PASSWORD_DEFAULT);

	 		//沒有重複 存資料
	 		$sql = $conn->prepare("INSERT INTO userdata (user_name, pass_word) VALUES (?, ?)");
			$sql->bind_param("ss",$user_name, $pass_word);
			$sql->execute();

			$return['error_msg'] ="";
	 		$return['active'] = 0;
	 		$return['method'] = "signup";
			$return['redirect'] = 'index.php';
			$_SESSION["user_name"] = $user_name;
			/*return['debug'] = "Sign up successful!";*/
			/*error_log("Reached here 1"); 
			echo "Reached here 2"; */

	 		echo json_encode($return,JSON_PRETTY_PRINT);

	 		$conn->close();
	 		exit();
	 	}

	 	// Log in
	 	else{
	 		$user_name = $_POST['user_name'];
	 		$pass_word = $_POST['pass_word'];
	 		$return=[];
	 		$isError = 0;
	 		//check if username has been already in the database
	 		$username_sql = $conn->prepare("SELECT pass_word FROM userdata WHERE user_name=?");
	 		$username_sql->bind_param("s",$user_name);
	 		$username_sql->execute();
	 		$username_sql->store_result();

	 		// has account
	 		if($username_sql->num_rows>0){
	 			$username_sql->bind_result($temp);
	 			$username_sql->fetch();
	 			$hash = (string) $temp;
				/*$verify_result = password_verify($pass_word, $hash);
				var_dump($verify_result);
				echo "hi";*/
				//echo "$pass_word, $hash";
	 			//check if the password is correct
	 			if(password_verify($pass_word, $hash)){
	 				$return['error_msg'] = "";
	 				$return['active'] = 0;
	 				$return['method'] = "login";
	 				$return['redirect'] = "index.php";
	 				$_SESSION["user_name"] = $user_name;
	 				echo json_encode($return,JSON_PRETTY_PRINT);
	 				exit;
	 			}
	 			else{
	 				$return['error_msg'] = "Wrong password !";
	 				$return['active'] = 1;
	 				echo json_encode($return,JSON_PRETTY_PRINT);
	 				exit;
	 			}
	 		}
	 		//cannot find the identical username
	 		else{
	 			$return['error_msg'] = "You don't have an account !";
	 			$return['active'] = 1;
	 			echo json_encode($return,JSON_PRETTY_PRINT);
	 			exit;
	 		}
	 	}
 	}
 	else
 		// Die. Kill the script.
		exit('Invalid URL');
?>